### ISSUE TITLE
Cocoapods support?

### ISSUE THREAD

**Issue by bezumkin** [yankodimitrov/SwiftKeychain#3]
Cocoapods are now [supports swift](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) in beta version.

Do you planning to add its support in SwiftKeychain? For example, here is [another packages](http://cocoapods.org/?q=on%3Aios%20Swift%20Keychain).

Thank you for awesome tool!

**Comment by yankodimitrov** [comment]
Just added the CocoaPods support! 

Thanks :)

**Comment by bezumkin** [comment]
Thank you!

I just moved SwiftKeychain from project files to Pods, it works!
